In [35]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [36]:
n=10

In [39]:
z = np.arange(n)[::-1]
z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [57]:
d = np.diag(z, k=0)
d

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
total_sum = 0

for i in range(len(d[0])):
    total_sum += d[i][i]
total_sum

45

In [46]:
sum(sum(d))

45

In [54]:
sum(np.diag(d))

45

In [52]:
n=9
x = np.arange(n)[::-1].reshape((3,3))
x

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [50]:
x = np.diag(np.diag(x))
x

array([[8, 0, 0],
       [0, 4, 0],
       [0, 0, 0]])

In [49]:
total_sum = 0

for i in range(len(x[0])):
    total_sum += x[i][i]
total_sum

12

In [34]:
sum(sum(x))

12

Задание 3
Решите систему уравнений:\
4x + 2y + z = 4\
x + 3y = 12\
5y + 4z = -3

In [58]:
from numpy import linalg

In [59]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [ [4], [12], [-3] ] )

In [61]:
linalg.solve(a, b)

array([[ 0.46666667],
       [ 3.84444444],
       [-5.55555556]])

In [62]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True